/* Main.c file generated by New Project wizard
 *
 * Created:   Thu Jul 11 2019
 * Processor: PIC16F877A
 * Compiler:  MPLAB XC8
 */

#include <xc.h>

void main(void)
 {
   // Write your code here
   while (1)
      ;
 }